
version: "3"

services:

  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Madrid
    ports:
      - "8200:8080"
    volumes:
      - ./fb-data:/data
      - ./fb-config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped

    
