
version: "3"

services:

  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - "8200:8080"
    volumes:
      - ./fb-data:/data
      - ./fb-config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped

    
